### ISSUE TITLE
Browsers

### ISSUE THREAD

**Issue by edpichler** [welcome-surf-trips/sunseaflower#10]
Funcionar nos principais browsers.

**Comment by edpichler** [comment]
Sugiro vc abrir no Safari pra ver....

**Comment by AlberthGDavid** [comment]
não tenho safari, o que esta acontecendo me mande um print se puder

**Comment by edpichler** [comment]
Instala ele plisss

**Comment by edpichler** [comment]
@AlberthDavid no safari nao funciona o "Enter" no submit.
