### ISSUE TITLE
Evento selecionado

### ISSUE THREAD

**Issue by edpichler** [welcome-surf-trips/sunseaflower#11]
O evento selecionado está com um quadrado azul no Chrome. Acho que é por causa do foco. Legal se conseguirmos evitar isso.

**Comment by edpichler** [comment]
@AlberthDavid nao fecha antes de eu ver blz, passa para eu validar antes.

**Comment by edpichler** [comment]
So pedir para eu validar..
Não precisa reassociar a tarefa a mim.

**Comment by AlberthGDavid** [comment]
Ah ok blz ;)
