### ISSUE TITLE
Icon Wait

### ISSUE THREAD

**Issue by edpichler** [welcome-surf-trips/sunseaflower#15]
Tico, ao clicar no "Signup", deveria ter um ícone do tipo "Wait" para dar feedback ao usuário que está sendo processado a requisição, entende?
Senão ele vai clicar varias vezes, achar q não funciona.

Assim como tem hoje ao clicar na galeria de imagens.

Mas tem q ver um iconezinho bonito, neutro, pode ser ate o msmo da galeria.

**Comment by AlberthGDavid** [comment]
Cara é tão rápido q nem compensa colocar um wait logo depois já abre o popup

**Comment by edpichler** [comment]
Aqui esta lento…. depende da internet local.

**Comment by edpichler** [comment]
@AlberthDavid esse aqui tu acha que não vale a pena mudar? Pode ser cara, mas, tenta simular com Internet lenta pra ti ver, por favor. Após simular, eu sigo a sua opinião. Quero ver se tu também concorda comigo. Na internet lenta da pousada eu clicava várias vezes.

**Comment by AlberthGDavid** [comment]
ok feito, não consegui simular muito bem aqui, quando puder teste por favor
