### ISSUE TITLE
Logos do rodapé alinhados a direita.

### ISSUE THREAD

**Issue by edpichler** [welcome-surf-trips/sunseaflower#6]
Alinhar a direita, como está no psd.

**Comment by AlberthGDavid** [comment]
não entendi, eles já estão alinhados a direita

**Comment by edpichler** [comment]
Veja que estão um pouco diferente do PSD.

![sea_sun_flower](https://cloud.githubusercontent.com/assets/358696/10220028/6cb8126e-681a-11e5-8e51-0d34a9370afd.png)

Se comparar fica fácil entender.

**Comment by AlberthGDavid** [comment]
OK!
