### ISSUE TITLE
Cinco meninas

### ISSUE THREAD

**Issue by edpichler** [welcome-surf-trips/sunseaflower#7]
Tem que aparecer as 5 meninas responsivo.

Tem tecnica pra isso, se quiser te ajudo a pesquisar. Não sei se vc não fez ainda por que tem algum impedimento ou se está faltando tempo mesmo.

**Comment by AlberthGDavid** [comment]
Já fiz deu uma melhorada, chega uma hora que fica difícil deixar as 5, veja e me diz o que achou

**Comment by edpichler** [comment]
@AlberthDavid vou encontrar o artigo q mostrava a técnica certa disso.

**Comment by edpichler** [comment]
Tico, olha como as imagens podem ser fluídas.

http://alistapart.com/article/responsive-web-design
Exemplo do artigo: http://alistapart.com/d/responsive-web-design/ex/ex-site-flexible.html

Do jeito que está no seasunflower.com já funciona, mas pensando a longo prazo, muitos celulares vão cair nessa tela. Podemos publicar do jeito que está, e melhorar na sequencia.

De qualquer forma, nos vamos utilizar essa técnica nos próximos sites que vierem, além do atual, pois o resultado eh muito bom. 

Espero que seja possível... isso não eh o mais prioritário nesse momento, pois o que tem já funciona ok?

**Comment by edpichler** [comment]
@AlberthDavid o pessoal ta achando que isso não é muito importante tico, então vamos deixar quieto ok.
